### ISSUE TITLE
non-void function 'php_svm_get_data_from_param' should return a value [-Wreturn-type]

### ISSUE THREAD

**Issue by ryandesign** [ianbarber/php-svm#2]
php-svm fails to build with the clang compiler, version 3.1:

```
svm-0.1.6/svm.c:454:4: error: non-void function 'php_svm_get_data_from_param' should return a value [-Wreturn-type]
                        php_stream_from_zval(stream, &zparam);
                        ^
/opt/local/include/php54/php/main/php_streams.h:262:44: note: expanded from macro 'php_stream_from_zval'
#define php_stream_from_zval(xstr, ppzval)      ZEND_FETCH_RESOURCE2((xstr), php_stream *, (ppzval), -1, "stream", php_file_le_stream(), php_file_le_pstream())
                                                ^
/opt/local/include/php54/php/Zend/zend_list.h:104:2: note: expanded from macro 'ZEND_FETCH_RESOURCE2'
        ZEND_VERIFY_RESOURCE(rsrc);
        ^
/opt/local/include/php54/php/Zend/zend_list.h:92:3: note: expanded from macro 'ZEND_VERIFY_RESOURCE'
                RETURN_FALSE;                                   \
                ^
/opt/local/include/php54/php/Zend/zend_API.h:626:44: note: expanded from macro 'RETURN_FALSE'
#define RETURN_FALSE                                    { RETVAL_FALSE; return; }
                                                                        ^
```
